# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("krige_pluie_journaliere works", {
  expect_true(inherits(krige_pluie_journaliere, "function")) 
})
