# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' create_sql_requete_calcule_somme
#'
#' @param con Connexion a la base de donnees meteo POSTGIS
#'
#' @return
#' créé la requête demandée dans la base POSTGIS des données météo
#' @export
#'
#' @examples
#' create_sql_requete_calcule_somme(con)
#' library(RPostgres)
#' library(yaml)
#' library(sf)
#'
#'
#' # Connexion à la base PostgreSQL
#' #config <- yaml::read_yaml("//etc//Vilaine_explorer//config.yml")
#' config <- yaml::read_yaml("C://workspace//gwilenalim//yaml//config.yml")
#'
#' # Connexion à la base PostgreSQL
#' con <- DBI::dbConnect(
#'   Postgres(),
#'   host = config$host,
#'   port = config$port,
#'   user = config$user,
#'   password = config$password,
#'   dbname = config$dbname
#' )
#'
#' create_sql_requete_calcule_somme(con)
create_sql_requete_calcule_somme <- function(con) {
  fonction_sql <- "
  CREATE OR REPLACE FUNCTION meteo.get_precipitations_par_station(
      date_debut DATE,
      date_fin DATE
  )
  RETURNS TABLE (
      id TEXT,
      altitude INTEGER,
      geometry GEOMETRY,
      somme_precipitations NUMERIC,
      nb_jours_donnees INTEGER,
      nb_jours_periode INTEGER,
      periode_debut DATE,
      periode_fin DATE
  ) AS $$
  BEGIN
      RETURN QUERY
      SELECT 
          s.id,
          CAST(s.alt AS INTEGER) AS altitude,
          s.geometry,
          SUM(d.\"RR\") AS somme_precipitations,
          COUNT(d.date)::INTEGER AS nb_jours_donnees,
          (date_fin - date_debut + 1)::INTEGER AS nb_jours_periode,
          MIN(d.date) AS periode_debut,
          MAX(d.date) AS periode_fin
      FROM 
          meteo.stations_meteo_france_quotidienne s
      JOIN 
          meteo.donnees_journalieres d ON s.id = d.id_station
      WHERE 
          d.\"RR\" IS NOT NULL
          AND d.date BETWEEN date_debut AND date_fin
      GROUP BY 
          s.id, s.alt, s.geometry
      HAVING 
          SUM(d.\"RR\") > 0;
  END;
  $$ LANGUAGE plpgsql STABLE;
  "

  dbExecute(con, fonction_sql)
}



