# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' get_nom_station_meteo
#'
#' @param con Connexion à la base de données PostgreSQL/PostGIS
#' @param ids Vector de codes de stations (id)
#'
#' @return Un data.frame avec les colonnes id et nom
#' @export
#'
#' @examples
#' \dontrun{
#' ids <- c("22001002", "22032002")
#' noms <- get_nom_station_meteo(con, ids)
#' }
get_nom_station_meteo <- function(con, ids) {
  # Construction de la requête SQL
  requete <- glue::glue_sql(
    "SELECT id, nom FROM meteo.stations_meteo_france_quotidienne WHERE id IN ({ids*})",
    ids = ids,
    .con = con
  )
  
  # Exécution de la requête
  resultats <- DBI::dbGetQuery(con, requete)
  
  return(resultats)
}

