# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Krigeage des précipitations journalières
#'
#' Cette fonction estime les précipitations journalières à une date donnée
#' pour un ensemble de points fournis sous forme d'objet `sf`, en utilisant
#' un modèle de krigeage basé sur les données de stations pluviométriques.
#'
#' @param objet_sf Un objet `sf` de type POINT, contenant les localisations pour lesquelles on souhaite estimer les précipitations.
#' @param date Date pour laquelle on veut exporter des données de précipitation. Format text type "%Y-%m-%d" ou Date ou POSIXct
#' @param con Une connexion à la base de données PostgreSQL contenant les données pluviométriques.
#'
#' @return Un vecteur numérique contenant, pour chaque point de `objet_sf`, la valeur estimée de précipitation (en mm) pour la date spécifiée.
#'
#' @examples
#' \dontrun{
#'library(RPostgres)
#'library(yaml)
#'
#'
#'# Connexion à la base PostgreSQL
#'#config <- yaml::read_yaml("//etc//Vilaine_explorer//config.yml")
#'config <- yaml::read_yaml("C://workspace//gwilenalim//yaml//config.yml")
#'
#'# Connexion à la base PostgreSQL
#'con <- DBI::dbConnect(
#'  Postgres(),
#'  host = config$host,
#'  port = config$port,
#'  user = config$user,
#'  password = config$password,
#'  dbname = config$dbname
#')
#'
#'# Coordonnées approximatives du centroïde de Rennes (en WGS84)
#'rennes_coords <- data.frame(
#'  lon = -1.6794,
#'  lat = 48.1147
#')
#'
#'# Créer un objet sf de type point en WGS84 (EPSG:4326)
#'rennes_sf <- st_as_sf(rennes_coords, coords = c("lon", "lat"), crs = 4326)
#'
#'# Reprojeter en Lambert 93 (EPSG:2154)
#'rennes_l93 <- st_transform(rennes_sf, crs = 2154)
#'
#'krige_pluie_journaliere(rennes_l93, 
#'                        date="2006-10-06", 
#'                        con=con)
#' library(RPostgres)
#' library(yaml)
#'
#'
#' # Connexion à la base PostgreSQL
#' #config <- yaml::read_yaml("//etc//Vilaine_explorer//config.yml")
#' config <- yaml::read_yaml("C://workspace//gwilenalim//yaml//config.yml")
#'
#' # Connexion à la base PostgreSQL
#' con <- DBI::dbConnect(
#'   Postgres(),
#'   host = config$host,
#'   port = config$port,
#'   user = config$user,
#'   password = config$password,
#'   dbname = config$dbname
#' )
#'
#' # Coordonnées approximatives du centroïde de Rennes (en WGS84)
#' rennes_coords <- data.frame(
#'   lon = -1.6794,
#'   lat = 48.1147
#' )
#'
#' # Créer un objet sf de type point en WGS84 (EPSG:4326)
#' rennes_sf <- st_as_sf(rennes_coords, coords = c("lon", "lat"), crs = 4326)
#'
#' # Reprojeter en Lambert 93 (EPSG:2154)
#' rennes_l93 <- st_transform(rennes_sf, crs = 2154)
#'
#'
#' krige_pluie_journaliere(rennes_l93, 
#'                         date="2006-10-06", 
#'                         con=con)
#'
#' @export
krige_pluie_journaliere <- function(objet_sf, date, con) {
  # Vérification des entrées
  if (!inherits(objet_sf, "sf")) {
    stop("L'objet fourni n'est pas un objet 'sf'.")
  }
  if (!all(sf::st_geometry_type(objet_sf) %in% c("POINT", "MultiPoint"))) {
    stop("L'objet 'sf' doit contenir uniquement des géométries de type POINT.")
  }
# Vérification des dates
  if (!inherits(date, c("Date", "POSIXct", "POSIXt", "character"))) {
    stop("date doit être de type Date, POSIXct ou character.")
  }

  # Conversion en format Date si nécessaire
  date <- as.Date(date)

  if (is.na(date)) {
    stop("La date doivent être au format Année-Mois-jour en text ou en date")
  }

 
  objet_sf<-sf::st_transform(objet_sf, 2154)
  
  
  # Récupération des données de précipitations
  pluvio <- pluviometrie_entre_2_dates(
    date_debut = date,
    date_fin = date,
    con = con,
    taux_completude = 1
  )

  # Chargement des données de terrain
  
  grd <- sf::read_sf(dsn=system.file("grd.gpkg", package = "meteo4Vilaine"))
  mnt <- terra::rast(system.file("mnt.tif", package = "meteo4Vilaine"))

  # Extraction de l'altitude pour les stations
  pluvio$altitude <- terra::extract(mnt, terra::vect(pluvio))[, 2]

  # Définition du modèle de variogramme
  vgm_model <- gstat::vgm(psill = 33.71, model = "Sph", range = 90593, nugget = 0.79)

  # Création du modèle de krigeage
  model <- gstat::gstat(
    id = "somme_precipitations",
    formula = somme_precipitations ~ altitude,
    data = pluvio,
    model = vgm_model
  )

  # Interpolation par krigeage
#  krige_result <- predict(model, newdata = grd)
  # Suppression du message d'information
krige_result <- suppressWarnings(suppressMessages(predict(model, newdata = grd)))


  # Extraction des valeurs interpolées pour les points d'intérêt
  return(round(valeurs_proches_sf(objet_sf, krige_result), 1))
}

