# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Krigeage des précipitations journalières
#'
#' Cette fonction estime les précipitations journalières à une date donnée
#' pour un ensemble de points fournis sous forme d'objet `sf`, en utilisant
#' un modèle de krigeage basé sur les données de stations pluviométriques.
#'
#' @param objet_sf Un objet `sf` de type POINT, contenant les localisations pour lesquelles on souhaite estimer les précipitations.
#' @param date Une date au format `Date` ou chaîne de caractères convertible en `Date`, correspondant au jour d'estimation.
#' @param con Une connexion à la base de données PostgreSQL contenant les données pluviométriques.
#'
#' @return Un vecteur numérique contenant, pour chaque point de `objet_sf`, la valeur estimée de précipitation (en mm) pour la date spécifiée.
#'
#' @examples
#' \dontrun{
#'   library(sf)
#'   pts <- st_as_sf(data.frame(x = c(1, 2), y = c(48, 49)), coords = c("x", "y"), crs = 4326)
#'   pts_l93 <- st_transform(pts, 2154)
#'   krige_pluie_journaliere(pts_l93, "2023-01-01", con)
#' }
#'
#' krige_pluie_journaliere()
#' @export
krige_pluie_journaliere <- function(objet_sf, date, con) {
  # Vérification des entrées
  if (!inherits(objet_sf, "sf")) {
    stop("L'objet fourni n'est pas un objet 'sf'.")
  }
  if (!all(sf::st_geometry_type(objet_sf) %in% c("POINT", "MultiPoint"))) {
    stop("L'objet 'sf' doit contenir uniquement des géométries de type POINT.")
  }
  if (is.character(date)) {
    date <- as.Date(date)
  }
  if (!inherits(date, "Date")) {
    stop("Le paramètre 'date' doit être une date valide.")
  }

  # Récupération des données de précipitations
  pluvio <- pluviometrie_entre_2_dates(
    date_debut = date,
    date_fin = date,
    con = con,
    taux_completude = 1
  )

  # Chargement des données de terrain
  
  grd <- sf::read_sf(dsn=system.file("grd.gpkg", package = "meteo4Vilaine"))
  mnt <- terra::rast(system.file("mnt.tif", package = "meteo4Vilaine"))

  # Extraction de l'altitude pour les stations
  pluvio$altitude <- terra::extract(mnt, terra::vect(pluvio))[, 2]

  # Définition du modèle de variogramme
  vgm_model <- gstat::vgm(psill = 33.71, model = "Sph", range = 90593, nugget = 0.79)

  # Création du modèle de krigeage
  model <- gstat::gstat(
    id = "somme_precipitations",
    formula = somme_precipitations ~ altitude,
    data = pluvio,
    model = vgm_model
  )

  # Interpolation par krigeage
#  krige_result <- predict(model, newdata = grd)
  # Suppression du message d'information
krige_result <- suppressMessages(predict(model, newdata = grd))


  # Extraction des valeurs interpolées pour les points d'intérêt
  return(round(valeurs_proches_sf(objet_sf, krige_result), 1))
}

