# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' pluviometrie_entre_2_dates
#'
#' @param date_debut Premier jour pour lequel on veut exporter des données de précipitation. Format text type "%Y-%m-%d"
#' @param date_fin Dernier jour pour lequel on veut exporter des données de précipitation. Format text type "%Y-%m-%d"
#' @param con Connexion a la base de donnees meteo POSTGIS#' 
#' @param taux_completude pourcentage de données disponibles pour que le résultat soit renvoyé. Exemple si le taux de complétude vaut 0.8 et qu'on lance une requête pour avoir els précipitations sur 5 jours, seuls les stations avec au moins 4 mesures de précipitations quotidiennes sur les 5 jours seront affichées
#'
#' @return
#' Interroge la base POSTGIS de données météo quotidiennes et renvoie un objet sf avec la date, l'identifiant de la station météo et la somme des précipitations entre les deux dates indiquées. 

#' @export
#'
#' @examples
#' pluviometrie_entre_2_dates(date_debut='1981-01-01', date_fin = '1981-01-01',con=con)
#' create_sql_requete_calcule_somme(con)
pluviometrie_entre_2_dates <- function(date_debut = '1980-01-01',
                                       date_fin = '1980-12-31',
                                       con = con,
                                       taux_completude = 1) {
  # Vérification des dates
  if (!inherits(date_debut, c("Date", "POSIXct", "POSIXt", "character"))) {
    stop("date_debut doit être de type Date, POSIXct ou character.")
  }
  if (!inherits(date_fin, c("Date", "POSIXct", "POSIXt", "character"))) {
    stop("date_fin doit être de type Date, POSIXct ou character.")
  }

  # Conversion en format Date si nécessaire
  date_debut <- as.Date(date_debut)
  date_fin <- as.Date(date_fin)

  if (is.na(date_debut) || is.na(date_fin)) {
    stop("Les dates doivent être valides et convertibles en format Date.")
  }

  if (date_debut > date_fin) {
    stop("date_debut doit être antérieure ou égale à date_fin.")
  }

  # Vérification de la connexion DBI
  if (!DBI::dbIsValid(con)) {
    stop("La connexion fournie n'est pas valide.")
  }

  # Vérification du taux de complétude
  if (!is.numeric(taux_completude) || taux_completude < 0 || taux_completude > 1) {
    stop("taux_completude doit être un nombre numérique entre 0 et 1.")
  }

  # Requête SQL
  requete_sql <- sprintf("
    SELECT * FROM meteo.get_precipitations_par_station('%s', '%s');
  ", date_debut, date_fin)

  # Lecture des résultats
  resultats_sf <- sf::st_read(con, query = requete_sql, quiet = TRUE)

  # Filtrage selon le taux de complétude
  resultats_sf <- subset(resultats_sf, 
                         nb_jours_donnees / nb_jours_periode >= taux_completude)

  return(resultats_sf)
}


