# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Précipitations par zone géographique
#'
#' Cette fonction calcule les précipitations journalières sur une zone donnée représentée par un objet sf.
#' Elle utilise les stations météo disponibles dans l'emprise ou effectue une interpolation si aucune station n'est présente.
#'
#' @param sf_objet Objet sf représentant la zone d'intérêt
#' @param date_debut Date de début de la période (au format Date ou chaîne de caractères)
#' @param date_fin Date de fin de la période (au format Date ou chaîne de caractères)
#' @param nb_jours Nombre de jours avant la date pour lesquels on souhaite récupérer les données
#' @param con Connexion à la base de données PostgreSQL/PostGIS
#'
#' @return Un data.frame avec les colonnes : date, precipitation_mm, source (nom de la station ou "donnée interpolée")
#' @export
#' @examples
#' \dontrun{
#' # Exemple d'utilisation de la fonction `precipitations_par_zone`
#' library(sf)
#'
#' # Définition d'une zone triangulaire autour de Rennes
#' triangle_sf <- st_sf(
#'  geometry = st_sfc(
#'      st_polygon(list(rbind(
#'        c(-1.6794, 48.1147),  # Rennes
#'        c(-1.2100, 48.1230),  # Vitré
#'        c(-1.5025, 47.6833),  # Derval
#'        c(-1.6794, 48.1147)   # Retour à Rennes
#'      )))
#'    ),
#'    crs = 4326
#'  )
#'
#'  # Appel de la fonction avec cette zone
#'  df <- precipitations_par_zone(triangle_sf, date_debut = "2022-01-01",date_fin = "2022-01-10", con = con)
#'
#'  # Définition d'un carré autour de Theix-Noyalo
#'  carre <- sf::st_sfc(st_point(c(-2.685, 47.616)), crs = 4326)
#'  carre <- sf::st_transform(carre, 2154)
#'
#'  half_side <- 25  # moitié du côté
#'  x <- sf::st_coordinates(carre)[1]
#'  y <- sf::st_coordinates(carre)[2]
#'
#'  carre <- st_polygon(list(rbind(
#'    c(x - half_side, y - half_side),
#'    c(x + half_side, y - half_side),
#'    c(x + half_side, y + half_side),
#'    c(x - half_side, y + half_side),
#'    c(x - half_side, y - half_side)
#'  )))
#'
#'  carre <- sf::st_sf(geometry = sf::st_sfc(carre), crs = 2154)
#'  df2 <- precipitations_par_zone(carre, date_debut = "2022-01-01",date_fin = "2022-01-10", con = con)
#' }
#'
precipitations_par_zone <- function(sf_objet, date_debut, date_fin, con) {

  library(sf)
  library(dplyr)
  library(glue)
  library(DBI)

  # 1. Calcul des dates
  date_debut<-as.Date(date_debut)
  date_fin<-as.Date(date_fin)
  dates <- seq(date_debut, date_fin, by = "day")

  # 2. Requête initiale pour récupérer les stations disponibles
  pluvio_temp <- pluviometrie_entre_2_dates(
    date_debut = date_debut,
    date_fin = date_fin,
    con = con,
    taux_completude = 0.8
  )

  # 3. Reprojection de sf_objet dans le CRS des données météo
  sf_objet <- sf::st_transform(sf_objet, sf::st_crs(pluvio_temp))

  # 4. Calcul du centroïde
  centroid <- sf::st_centroid(sf_objet)

  # 5. Sélection de la station la plus proche du centroïde et dans l'emprise
  stations_dans_zone <- sf::st_intersection(pluvio_temp, sf_objet)

  # Initialisation du dataframe de sortie
  df_sortie <- data.frame(date = as.Date(character()), precipitation_mm = numeric(), source = character())

  if (nrow(stations_dans_zone) > 0) {
    stations_dans_zone$distance <- sf::st_distance(stations_dans_zone, centroid)
    station_ref <- stations_dans_zone %>% slice_min(order_by = distance, n = 1)
    id_station_ref <- station_ref$id

    # 6. Requête SQL pour récupérer les données journalières
    query <- glue::glue("
      SELECT 
        date,
        \"RR\" AS precipitation_mm,
        id_station AS source
      FROM meteo.donnees_journalieres
      WHERE id_station = '{id_station_ref}'
        AND date BETWEEN '{date_debut}' AND '{date_fin}'
    ")

    df_sortie <- DBI::dbGetQuery(con, query)
  }

  # 7. Complément par interpolation pour les dates manquantes
  dates_manquantes <- setdiff(dates, as.Date(df_sortie$date))

  if (length(dates_manquantes) > 0) {
    for (date_i in dates_manquantes) {
      krige_i <- krige_pluie_journaliere(centroid, date = date_i, con = con)

      df_sortie <- bind_rows(df_sortie, data.frame(
        date = date_i,
        precipitation_mm = krige_i,
        source = "donnée interpolée"
      ))
    }
  }

  # 8. Ajout des noms des stations
  noms_stations <- get_nom_station_meteo(con, unique(df_sortie$source[df_sortie$source != "donnée interpolée"]))
  df_sortie <- df_sortie %>%
    left_join(noms_stations, by = c("source" = "id")) %>%
    mutate(source = ifelse(is.na(nom), source, nom)) %>%
    select(date, precipitation_mm, source)

  return(df_sortie)
}

