# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' valeurs_proches_sf
#' On injecte un objet sf de type points (points_sf). 
#' En retour la fonction recherche, pour chaque élément de points_sf quel est le point de la couche ref_sf le plus proche. Il renvoie alors la valeur contenue dans la colonne "col_valeur" de ref_sf
#'
#' @param points_sf Un objet sf de type POINT (les points à interroger)
#' @param ref_sf Un objet sf contenant les points de référence et une colonne de valeurs
#' @param col_valeur Le nom de la colonne contenant les valeurs à extraire (chaîne de caractères)
#'
#' @return Un vecteur des valeurs les plus proches pour chaque point
#' @export
valeurs_proches_sf <- function(points_sf, ref_sf, col_valeur = "somme_precipitations.pred") {
  # Vérifications

# Vérification des types
 if (!inherits(points_sf, "sf")) {
stop("L'argument 'points_sf' doit être un objet 'sf'.")
}
if (!inherits(ref_sf, "sf")) {
stop("L'argument 'ref_sf' doit être un objet 'sf'.")
}

# Vérification des géométries
 if (!all(sf::st_geometry_type(points_sf) %in% c("POINT", "MultiPoint"))) {
 stop("L'objet 'points_sf' doit contenir uniquement des géométries de type POINT ou MultiPoint.")
 }
 if (!all(sf::st_geometry_type(ref_sf) %in% c("POINT", "MultiPoint"))) {
 stop("L'objet 'ref_sf' doit contenir uniquement des géométries de type POINT ou MultiPoint.")
 }

 # Vérification de la colonne de valeur
 if (!is.character(col_valeur) || length(col_valeur) != 1) {
 stop("L'argument 'col_valeur' doit être une chaîne de caractères de longueur 1.")
 }
 if (!(col_valeur %in% names(ref_sf))) {
 stop(sprintf("La colonne '%s' n'existe pas dans 'ref_sf'.", col_valeur))
 }

  
  # Harmoniser les CRS
  if (!sf::st_crs(points_sf) == sf::st_crs(ref_sf)) {
    points_sf <- sf::st_transform(points_sf, sf::st_crs(ref_sf))
  }
  
  # Trouver les indices des points les plus proches
  idx <- sf::st_nearest_feature(points_sf, ref_sf)
  
  # Extraire les valeurs correspondantes
  valeurs <- ref_sf[[col_valeur]][idx]
  
  return(valeurs)
}

