# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' valeurs_proches_sf
#' Extraire les valeurs les plus proches depuis un objet sf de référence
#'
#' @param points_sf Un objet sf de type POINT (les points à interroger)
#' @param ref_sf Un objet sf contenant les points de référence et une colonne de valeurs
#' @param col_valeur Le nom de la colonne contenant les valeurs à extraire (chaîne de caractères)
#'
#' @return Un vecteur des valeurs les plus proches pour chaque point
#' @export
valeurs_proches_sf <- function(points_sf, ref_sf, col_valeur = "somme_precipitations.pred") {
  # Vérifications
  stopifnot(inherits(points_sf, "sf"))
  stopifnot(inherits(ref_sf, "sf"))
  stopifnot(col_valeur %in% names(ref_sf))
  
  # Harmoniser les CRS
  if (!sf::st_crs(points_sf) == sf::st_crs(ref_sf)) {
    points_sf <- sf::st_transform(points_sf, sf::st_crs(ref_sf))
  }
  
  # Trouver les indices des points les plus proches
  idx <- sf::st_nearest_feature(points_sf, ref_sf)
  
  # Extraire les valeurs correspondantes
  valeurs <- ref_sf[[col_valeur]][idx]
  
  return(valeurs)
}

